export const filters = [
  {
    id: 1,
    filter: "SIZE",
    options: [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "1",
      "2",
      "3",
      "5",
      "6",
      "8",
      "10",
      "12",
      "14",
      "14",
      "1M",
      "6M",
      "9M",
      "12M",
      "18M",
      "24M",
      "ADULT M/L",
      "KXXL",
      "NS",
    ],
  },
  {
    id: 2,
    filter: "COLOR",
    options: [
      "BLUE",
      "NAVY BLUE",
      "BEIGE",
      "WHITE",
      "CORAL",
      "GOLD",
      "GREY",
      "BROWN",
      "MELANGE",
      "BLACK",
      "SILVER",
      "RED",
      "ROSE",
      "TRANSPARENT",
      "GREEN",
    ],
  },
  {
    id: 3,
    filter: "MATCHWEAR",
    options: ["HOME JERSEY"],
  },
  {
    id: 4,
    filter: "GENRE",
    options: ["MALE", "CHILDREN", "FEMALE", "YOUTH", "UNISEX"],
  },
  {
    id: 5,
    filter: "PRODUCT TYPE",
    options: [
      "HOME ACCESSORIES",
      "COMPUTER ACCESSORIES",
      "SCHOOL ACCESSORIES",
      "PET ACCESSORIES",
      "CARPETS",
      "BIBS",
      "BALLS FROM FOOTBAL",
      "FLAGS",
      "PENNANTS",
      "BODIES",
      "SNOWBALLS",
      "BALLPOINT PENS",
      "BAGS",
      "BOTTLES",
      "NECK PANTIES",
      "SCARVES",
      "SOCKS",
      "T-SHIRTS",
      "TANK TOPS",
      "HOUSINGS",
      "PORTFOLIOS",
      "ASHTRAYS",
      "TRACKSUITS",
      "JACKETS",
      "DUMMIES",
      "NECKLACES",
      "CONTAINERS",
      "LANYARDS",
      "NOTEBOOKS",
      "KITS",
      "SHIN GUARDS",
      "COVERS",
      "GLASSES",
      "CUFFLINKS",
      "CAPS",
      "CAPS",
      "MONEY BOXES",
      "GAMES",
      "TOYS",
      "KEY RINGS",
      "MASKS",
      "BACKPACKS",
      "TOILET BAGS",
      "BOTTOMS",
      "UMBRELLAS",
      "EARRINGS",
      "PINS",
      "POSTERS",
      "BRACELETS",
      "WATCHES",
      "SACK",
      "HOODIES",
      "CUPS",
      "THERMOS FLASKS",
      "TOWELS",
    ],
  },
  // {
  //   filter: "DATE: RECENT TO OLD",
  //   options: [
  //     "SORT BY",
  //     "BEST SELLERS",
  //     "ALPHABETICALLY, A-Z",
  //     "ALPHABETICALLY, Z-A",
  //     "PRICE: LOWEST TO HIGHEST",
  //     "PRICE: HIGHEST TO LOWEST",
  //     "DATE: OLD TO RECENT",
  //     "DATE: RECENT TO OLD",
  //   ],
  // },
];
